WIP TC-1130 FAO Carlos: example of data structure returned
trustification/trustification pull request #1550
Opened 2024-07-09 19:08 UTC by m-brophy

2024-07-12 18:32 UTC, carlosthe19916 approved these changes
@m-brophy my apologies for the late review.

This is the exact JSON I get from the backend:

```json
[
  [
    "sbom1", // array[0] is a string
    [// array[1] is another array
      {
        "severity": "none",
        "count": 3
      },
      {
        "severity": "low",
        "count": 5
      },
      {
        "severity": "medium",
        "count": 10
      },
      {
        "severity": "high",
        "count": 4
      },
      {
        "severity": "critical",
        "count": 2
      }
    ]
  ],
  [
    "sbom2",
    [
      {
        "severity": "none",
        "count": 3
      },
      {
        "severity": "low",
        "count": 5
      },
      {
        "severity": "medium",
        "count": 10
      },
      {
        "severity": "high",
        "count": 4
      },
      {
        "severity": "critical",
        "count": 2
      }
    ]
  ],
  [
    "sbom3",
    [
      {
        "severity": "none",
        "count": 3
      },
      {
        "severity": "low",
        "count": 5
      },
      {
        "severity": "medium",
        "count": 10
      },
      {
        "severity": "high",
        "count": 4
      },
      {
        "severity": "critical",
        "count": 2
      }
    ]
  ]
]
```

If you notice the second array contains "sbom1" and another array in the same array. Could we change it?

I could propose something like:

```json
[
    {
        "sbom_id": "something",
        "sbom_name": "Quarkus-v1",
        "vulnerabilities": {
            "none": 3,
            "low": 3,
            "medium": 0,
            "high": 3,
            "critical": 3
        }
    }
]
```

2024-07-17 21:17 UTC, carlosthe19916 requested changes
.

2024-08-21 22:59 UTC, carlosthe19916 commented
@m-brophy I have created a PR to your branch with what I think is  working version of "last 10 sboms with vulnerabilities". If it helps please take a look at it, there might be place for improvement and of course we should test and check if it works or not https://github.com/m-brophy/trustification/pull/1

2024-08-23 09:07 UTC, bxf12315 commented on bombastic/api/src/server.rs
> +async fn sbom_status(
I have a suggestion: there is no need to create a new endpoint, we can just utilize the existing one.[1] 

[1] https://github.com/trustification/trustification/blob/621fc8abc1b67a25686e635a1f9ac5319a845b82/bombastic/api/src/server.rs#L235

2024-08-27 21:32 UTC, carlosthe19916 approved these changes

2024-08-28 13:21 UTC, carlosthe19916 commented
Thanks for the PR https://github.com/trustification/trustification/pull/1716 @mrizzi !

2024-08-28 13:21 UTC, merged