TC-1130 create status endpoint for dashbaord
trustification/trustification pull request #1576
Opened 2024-07-16 12:41 UTC by bxf12315

2024-07-30 14:50 UTC, carlosthe19916 requested changes
@bxf12315 first of all, my sincere apologies for my very late review. I just came back from PTO.

For for the UI. The most important endpoint is `/api/v1/dashboard/status` thanks for creating it. May I suggest some enhancements please?

Currently this is the response I get from the backend:

```json
{
  "sbom_summary": {
    "total_sboms": 13,
    "last_updated_sbom": "f9e65eab-b62f-4f0c-ac68-7b78d25cc67d",
    "last_updated_date": [
      2024,
      212,
      14,
      40,
      7,
      842115000,
      0,
      0,
      0
    ]
  },
  "csaf_summary": {
    "total_csafs": 7,
    "last_updated_csaf": "CVE-2023-20862",
    "last_updated_date": [
      2024,
      212,
      14,
      41,
      33,
      163200000,
      0,
      0,
      0
    ]
  },
  "cve_summary": {
    "total_cves": 34,
    "last_updated_cve": "CVE-2023-5370",
    "last_updated_date": [
      2024,
      212,
      14,
      36,
      53,
      433839000,
      0,
      0,
      0
    ]
  }
}
```
The problem I see is that for SBOMs and CSAF files, there is the ID and NAME of the file which are not necessarily the same. How to reproduce it:

-  Start this PR locally
- Upload the following SBOM manually [seedwing-java-example.json](https://github.com/user-attachments/files/16429671/seedwing-java-example.json)

- 
- Hit the endpoint `/api/v1/dashboard/status`

As you can see the field `sbom_summary.last_updated_sbom` is an uuid and not a name.

Could we please change the current response to:

```json
{
  "sbom_summary": {
    "total_sboms": 123,
    "last_updated_sbom_id": "SBOM_ID",
    "last_updated_sbom_name": "SBOM_NAME",
    "last_updated_date": date
  },
  "csaf_summary": {
    "total_csafs": 123,
    "last_updated_csaf_id": "CSAF_ID",
    "last_updated_csaf_name": "CSAF_NAME",
    "last_updated_date": DATE
  },
  "cve_summary": {
    "total_cves": 123,
    "last_updated_cve": "CVE_ID",
    "last_updated_date": DATE
  }
}
```

> Note: the current dates returning from the backend are arrays, which is not correct. But this is an issue that already exists in multiple places of the whole set of of rest endpoints. I think I can survive with the current dates as an array, no need to change it unless we find difficulties.

2024-08-07 07:55 UTC, bxf12315 commented
> @bxf12315 first of all, my sincere apologies for my very late review. I just came back from PTO.
> 
> For for the UI. The most important endpoint is `/api/v1/dashboard/status` thanks for creating it. May I suggest some enhancements please?
> 
> Currently this is the response I get from the backend:
> 
> ```json
> {
>   "sbom_summary": {
>     "total_sboms": 13,
>     "last_updated_sbom": "f9e65eab-b62f-4f0c-ac68-7b78d25cc67d",
>     "last_updated_date": [
>       2024,
>       212,
>       14,
>       40,
>       7,
>       842115000,
>       0,
>       0,
>       0
>     ]
>   },
>   "csaf_summary": {
>     "total_csafs": 7,
>     "last_updated_csaf": "CVE-2023-20862",
>     "last_updated_date": [
>       2024,
>       212,
>       14,
>       41,
>       33,
>       163200000,
>       0,
>       0,
>       0
>     ]
>   },
>   "cve_summary": {
>     "total_cves": 34,
>     "last_updated_cve": "CVE-2023-5370",
>     "last_updated_date": [
>       2024,
>       212,
>       14,
>       36,
>       53,
>       433839000,
>       0,
>       0,
>       0
>     ]
>   }
> }
> ```
> 
> The problem I see is that for SBOMs and CSAF files, there is the ID and NAME of the file which are not necessarily the same. How to reproduce it:
> 
> * Start this PR locally
> * Upload the following SBOM manually [seedwing-java-example.json](https://github.com/user-attachments/files/16429671/seedwing-java-example.json)
> * Hit the endpoint `/api/v1/dashboard/status`
> 
> As you can see the field `sbom_summary.last_updated_sbom` is an uuid and not a name.
> 
> Could we please change the current response to:
> 
> ```json
> {
>   "sbom_summary": {
>     "total_sboms": 123,
>     "last_updated_sbom_id": "SBOM_ID",
>     "last_updated_sbom_name": "SBOM_NAME",
>     "last_updated_date": date
>   },
>   "csaf_summary": {
>     "total_csafs": 123,
>     "last_updated_csaf_id": "CSAF_ID",
>     "last_updated_csaf_name": "CSAF_NAME",
>     "last_updated_date": DATE
>   },
>   "cve_summary": {
>     "total_cves": 123,
>     "last_updated_cve": "CVE_ID",
>     "last_updated_date": DATE
>   }
> }
> ```
> 
> > Note: the current dates returning from the backend are arrays, which is not correct. But this is an issue that already exists in multiple places of the whole set of of rest endpoints. I think I can survive with the current dates as an array, no need to change it unless we find difficulties.

For the OffsetDateTime,  I found some code [1] and [2] , This should work according to the original handling method. Is it right?



[1] https://github.com/trustification/trustification/blob/a79f304f21179238dbad9dd190e83b7c5e8ed0c7/spog/ui/crates/common/src/utils/time.rs#L6
[2] https://github.com/trustification/trustification/blob/6517e794b999ccadd29dd26899cd9060b4adfc4a/spog/ui/src/pages/cve/result/products.rs#L115

2024-08-07 21:08 UTC, carlosthe19916 requested changes
@bxf12315 thanks for your PR, looks good. Sorry to keep asking changes but would it be possible to:
- Move your `DashboardStatus` struct under the models folder here https://github.com/trustification/trustification/tree/main/spog/model/src ?The reason is that it is the only folder that the UI gets access to and the models will be reused in the UI side
- About the DATEs. I do not think it is a problem if the dates are on the form of an array. I know that is technically a bad thing to do in the rest endpoint, but there are other endpoints that are doing the same and there is code to be reused in order to read Dates as Arrays, if it is easier let's not make problems and use the Date as arrays, unless anyone opposes :)

2024-08-08 10:12 UTC, bxf12315 commented
> @bxf12315 thanks for your PR, looks good. Sorry to keep asking changes but would it be possible to:
> 
> * Move your `DashboardStatus` struct under the models folder here https://github.com/trustification/trustification/tree/main/spog/model/src ?The reason is that it is the only folder that the UI gets access to and the models will be reused in the UI side
> * About the DATEs. I do not think it is a problem if the dates are on the form of an array. I know that is technically a bad thing to do in the rest endpoint, but there are other endpoints that are doing the same and there is code to be reused in order to read Dates as Arrays, if it is easier let's not make problems and use the Date as arrays, unless anyone opposes :)

sure.

2024-08-08 10:50 UTC, bxf12315 commented
@carlosthe19916 Done

2024-08-08 16:38 UTC, carlosthe19916 approved these changes

2024-08-08 17:41 UTC, carlosthe19916 commented
@bxf12315 Thanks for the latest changes. The mock-ups show dates in a specific format which does not currently match the return string value of the backend. Currently I see dates like `2024-08-08`. I think we have some options:
- Either return a string just like now, but using the format requested in the mockups OR
- Return the date as an "Array" as you initially did in your first commit and let the client parse that array into a date (currently there are other endpoints returning arrays as dates, for instance the endpoint http://localhost:8083/api/v1/advisory/search is returning an array, and this is code done originally by the original maintainers so given the short life of this repo we can do the same I think)

![image](https://github.com/user-attachments/assets/41e5ee7b-f3a1-47e0-bd0a-7374d367cf11)

2024-08-09 01:07 UTC, bxf12315 commented
> @bxf12315 Thanks for the latest changes. The mock-ups show dates in a specific format which does not currently match the return string value of the backend. Currently I see dates like `2024-08-08`. I think we have some options:
> 
> * Either return a string just like now, but using the format requested in the mockups OR
> * Return the date as an "Array" as you initially did in your first commit and let the client parse that array into a date (currently there are other endpoints returning arrays as dates, for instance the endpoint http://localhost:8083/api/v1/advisory/search is returning an array, and this is code done originally by the original maintainers so given the short life of this repo we can do the same I think)
> 
> ![image](https://private-user-images.githubusercontent.com/2582866/356323765-41e5ee7b-f3a1-47e0-bd0a-7374d367cf11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjU4MjksIm5iZiI6MTcyMzE2NTUyOSwicGF0aCI6Ii8yNTgyODY2LzM1NjMyMzc2NS00MWU1ZWU3Yi1mM2ExLTQ3ZTAtYmQwYS03Mzc0ZDM2N2NmMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMDEwNTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTYxNGY0YjkyYTk4YmYyZTJlZWJlMWVmNmM2NTc1NmIwMTFjNWRlNWZlYzdmZTM4NzUzYjQ4NWFjNWJhZDVhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FWg2LoXm1K-Jqmd98DO93W2jEX-xSb9cxfQ6QabT07I)

To maintain code consistency, I suggest continuing to use the original method. Follow [1]

[1] https://github.com/trustification/trustification/blob/a79f304f21179238dbad9dd190e83b7c5e8ed0c7/spog/ui/crates/common/src/utils/time.rs#L6

2024-08-19 18:31 UTC, carlosthe19916 commented
Thanks for the changes @bxf12315 . I just changed the title and description of this PR to point to the right JIRA tickets. I will merge this PR now. Thanks!!

2024-08-19 18:31 UTC, merged