Allow testing CI locally with act
trustification/trustification pull request #476
Opened 2023-09-04 13:40 UTC by i386x

Adjust `.github/workflows/ci.yaml` and related files so it can be tested locally using `act` tool and describe the process in `DEVELOPING.md`.

2023-09-04 14:07 UTC, ctron requested changes

2023-09-13 15:26 UTC, i386x commented on .github/workflows/ci.yaml
> +      - uses: actions-rs/toolchain@v1
@ctron thanks for the note, I made a local action for that. Just to be clear this PR should have no effect on what is running inside GitHub CI (due to the `if: ${{ env.ACT }}` conditions). Also `act` does not use original GitHub-maintained Ubuntu images but Ubuntu images maintained by `act` upstream (they are very similar but not the same).

2023-09-19 13:46 UTC, jcrossley3 requested changes
What problem are we solving with act?

2023-09-20 07:29 UTC, ctron commented on .github/workflows/ci.yaml
> +      - uses: actions-rs/toolchain@v1
>  Also act does not use original GitHub-maintained Ubuntu images but Ubuntu images maintained by act upstream (they are very similar but not the same).

That makes a bit uncomfortable. As it kind of voids the idea of running the same (the exact same) workflow locally.

It feels we're adding a lot of stuff, and I don't really see the benefit.

2023-10-16 07:20 UTC, i386x commented
Since we are using `xtask` now, this change is no longer needed as everything we need to do (in context of project development/testing) can be managed by `cargo` and some `xtask` action.

2023-10-16 07:20 UTC, closed without merging