Guac replicas config
trustification/trustification pull request #905
Opened 2023-11-29 11:52 UTC by desmax74

Guac replicas configuration to enable configuration on Openshift

2023-11-29 11:57 UTC, dejanb requested changes
I think this should be changed in the chart

https://github.com/trustification/trustification/blob/main/deploy/k8s/chart/templates/guac/graphql/030-Deployment.yaml#L11

and then template be rebuilt 

https://github.com/trustification/trustification/blob/main/deploy/openshift/DEVELOPING.md

2023-11-29 13:23 UTC, ctron requested changes

2023-11-29 13:35 UTC, ctron reviewed
LGTM, but I'll leave it for others.

2023-11-29 13:55 UTC, desmax74 commented
/hold for sre merge

2023-11-30 07:43 UTC, dejanb approved these changes

2023-11-30 07:43 UTC, merged